model:
  id: qwen-max
  name: "Qwen: Qwen-Max "
  lab: qwen
  family: qwen
  service: openrouter

capabilities:
  context_window: 32768
  max_output_tokens: 8192
  multimodal: false
  vision: false
  functions: false
  json_mode: false
  streaming: true
  system_prompt: true

pricing:
  currency: USD
  input_per_1k_tokens: 0.0015999999999999999
  output_per_1k_tokens: 0.0063999999999999994
