model:
  id: command-r-plus-08-2024
  name: "Cohere: Command R+ (08-2024)"
  lab: cohere
  family: command
  service: openrouter

capabilities:
  context_window: 128000
  max_output_tokens: 4000
  multimodal: false
  vision: false
  functions: false
  json_mode: false
  streaming: true
  system_prompt: true

pricing:
  currency: USD
  input_per_1k_tokens: 0.0025
  output_per_1k_tokens: 0.01
